import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const envPath = path.resolve(process.cwd(), '.env.local');
const envContent = fs.readFileSync(envPath, 'utf8');

const getEnvValue = (key: string) => {
    const match = envContent.match(new RegExp(`^${key}=(.*)$`, 'm'));
    return match ? match[1].trim() : null;
};

const supabaseUrl = getEnvValue('SUPABASE_URL') || getEnvValue('NEXT_PUBLIC_SUPABASE_URL');
const supabaseKey = getEnvValue('SUPABASE_SERVICE_ROLE_KEY');

const supabase = createClient(supabaseUrl!, supabaseKey!);

async function refreshData() {
    console.log('Fetching all locations...');
    const { data: locations, error: locError } = await supabase.from('wards').select('id, city');

    if (locError) {
        console.error('Error fetching locations:', locError);
        return;
    }

    console.log(`Found ${locations.length} locations. Generating fresh readings...`);

    const now = new Date();
    const readings = locations.map(loc => {
        let baseAqi = 100 + (loc.city.length * 10) % 200;
        if (loc.city === 'Delhi') baseAqi = 350;
        if (loc.city === 'Mumbai') baseAqi = 180;

        const aqi = Math.round(baseAqi + (Math.random() - 0.5) * 50);
        const anomalyScore = aqi > 250 ? 7 + Math.random() * 3 : aqi > 150 ? 4 + Math.random() * 3 : Math.random() * 3;

        return {
            location_id: loc.id,
            aqi_value: aqi,
            anomaly_score: anomalyScore,
            pm25: aqi * 0.6 + (Math.random() - 0.5) * 20,
            pm10: aqi * 1.2 + (Math.random() - 0.5) * 30,
            source: 'iot',
            recorded_at: now.toISOString()
        };
    });

    const chunkSize = 100;
    for (let i = 0; i < readings.length; i += chunkSize) {
        const chunk = readings.slice(i, i + chunkSize);
        const { error } = await supabase.from('aqi_readings').insert(chunk);
        if (error) console.error(`Error inserting readings chunk ${i}:`, error.message);
    }

    // Generate some pollution sources for high aqi locations
    const highAqiReadings = readings.filter(r => r.aqi_value > 200);
    const sources = highAqiReadings.map(r => {
        const types = ['traffic', 'construction', 'industrial', 'biomass_burning'];
        const type = types[Math.floor(Math.random() * types.length)];
        return {
            location_id: r.location_id,
            source_type: type,
            confidence_score: 0.7 + Math.random() * 0.3,
            detected_at: now.toISOString(),
            raw_features: { note: 'Generated by script' }
        };
    });

    if (sources.length > 0) {
        const { error } = await supabase.from('pollution_sources').insert(sources);
        if (error) console.error('Error inserting sources:', error.message);
    }

    console.log(`Success! Inserted ${readings.length} fresh readings and ${sources.length} pollution sources at ${now.toISOString()}`);

}

refreshData().catch(console.error);
